name: test-container-job
on: workflow_dispatch
permissions:
  contents: read

jobs:
  # this sucks. can't checkout repo then invoke container with volume of
  # repo. so:
  # - checkout repo
  # - docker run with volume mounts input/output directories
  # - docker moves files to output directory so this script is ignorant of dir structure
  # - this script collects built files

  build:
    strategy:
      matrix:
        image: [almalinux-devtoolset11, linux-arm64, alpine]
    name: Building ${{ matrix.image }} binaries
    runs-on: ubuntu-latest

    timeout-minutes: 20
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      # - name: Setup node
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: 20
      # - name: Install dependencies
      #   run: npm install

      - name: Build binaries
        run: |
          docker run --rm -v ${{ github.workspace }}:/repo -w /repo ghcr.io/contrast-security-oss/${{ matrix.image }}:latest
      - name: Show files
        run: find ${{ github.workspace }}
